# Arreglos y Clases

## Matrices

Una matriz es un arreglo de n por n elementos

\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \dots & a_{nn}
\end{bmatrix}

In [1]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
#Vamos a crear  otra lista de listas
B=[[21,34,40],[71,17,77],[73,81,28]]
print(A,B)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]] [[21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [3]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
A[0][0]
[1,2,3]
#A[0][0]

1

##Vectores y Listas

In [7]:
L=A[0]
M=B[0]
print(L,M)

[1, 2, 3] [21, 34, 40]


In [8]:
a=L[0]
b=M[0]
a+b

22

In [9]:
a==1

True

### Suma de Vectores

In [10]:
len(L)==len(M)

True

In [11]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
print(suma)

[22, 36, 43]


Suma

In [ ]:
suma=[L[i]+M[i] for i in range (3)]
print(suma)

#### Creacion de funciones globales

La funcion para crear funciones es `def`que se cierra con un debug (`print` o `return`)

In [14]:
def Hola():
  print("Hola me llamo Juanma")

In [16]:
Hola()

Hola me llamo Juanma


In [28]:
def Saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")


In [29]:
Saludar ("Juanma", 18)

Hola, me llamo Juanma y tengo 18 años


In [39]:
def par():
  for x in range(10):
    if x%2==0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [41]:
par()

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [43]:
def suma_vectorial (L,M):
  x = [L[i]+M[i] for i in range (len(L))]
  return x



In [44]:
L=[1,2,3]
M=[21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

## Modulos o librerias

In [46]:
import math
from math import sqrt, pi

In [48]:
sqrt(68)

8.246211251235321

In [49]:
pi

3.141592653589793

# El Modulo NumPy

La funcion array

In [50]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector+M_vector

array([22, 36, 43])

In [51]:
C= [0,2,2,2,3,3,2,17,2]
A=[8,1,1,1,2,2,1,16,1]

C_matriz= np.array (C).reshape(3,3)
A_matriz= np.array (A).reshape(3,3)

print (C_matriz)
print (A_matriz)

[[ 0  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [52]:
C_matriz @ A_matriz

array([[ 4, 36,  6],
       [22, 56, 11],
       [35, 68, 38]])

In [53]:
A_matriz @ C_matriz

array([[ 4, 36, 21],
       [ 8, 42, 12],
       [34, 67, 52]])